version: '3.8'

services:
  development:
    build:
      args:
        UIDGID: ${UIDGID}
        USER: ${USER}
        REPO: ${REPO}
      context: .
      dockerfile: Dockerfile
    command: bash -c "source /opt/upstream/install/setup.sh &&
                      colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml &&
                      colcon mixin add ${REPO} file:///opt/colcon-mixin/index.yaml &&
                      colcon mixin update &&
                      export PATH="/usr/lib/ccache:$PATH" &&
                      bash"
    container_name: ${USER}-${REPO}-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=0
      - TERM=xterm-256color
    extra_hosts:
      - ${REPO}-dev:127.0.0.1
    hostname: ${REPO}-dev
    image: ${REPO}-dev:latest
    network_mode: host
    privileged: true
    user: ${UIDGID}
    volumes:
      - ~/.ssh:${HOME}/.ssh:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
      - ${PWD}:${HOME}/ws/src/${REPO}
      - ~/.${REPO}/ccache:${HOME}/.ccache
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${HOME}/ws
