name: ci

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  ros:
    strategy:
      matrix:
        ros_distro: [foxy, humble, rolling]
    runs-on: ubuntu-latest
    container: ghcr.io/picknikrobotics/ros_testing_templates:upstream-${{ matrix.ros_distro }}
    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Cache ccache
        uses: pat-s/always-upload-cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-ros-${{ matrix.ros_distro }}-${{ github.sha }}-${{ github.run_id }}
          restore-keys: |
            ccache-ros-${{ matrix.ros_distro }}-${{ github.sha }}
            ccache-ros-${{ matrix.ros_distro }}
      - uses: ros-tooling/setup-ros@v0.4.1
      - uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: ${{ matrix.ros_distro }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["ccache", "lld"]
              }
            }
