name: docker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - '.github/workflows/docker.yaml'
      - 'ros2/Dockerfile'
      - 'ros2/upstreams.repos'
      - 'ros2/compose.dev.yml'
      - '**/package.xml'

jobs:
  upstream:
    strategy:
      matrix:
        ros_distro: [foxy, humble, rolling]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ros2
          file: ros2/Dockerfile
          push: true
          target: upstream
          build-args: |
            ROS_DISTRO=${{ matrix.ros_distro }}
            REPO=ros_testing_templates
          tags: ghcr.io/picknikrobotics/ros_testing_templates:upstream-${{ matrix.ros_distro }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
