name: naive_tests

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  naive_tests:
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
    defaults:
      run:
        shell: bash

    steps:
    # - name: Setup ROS 2 Environment
    #   uses: ros-tooling/setup-ros@v0.7
    #   with:
    #     required-ros-distributions: humble

    - name: Checkout repository
      run: |
        mkdir -p src
        cd src
        git clone --single-branch --branch bgill92/update-naive-example https://github.com/PickNikRobotics/ros_testing_templates.git
        cd ..

    - name: Build the workspace
      run: |
        source /opt/ros/humble/setup.bash
        colcon build --packages-select naive naive_superclass

    - name: Run tests
      run: |
        source /opt/ros/humble/setup.bash
        colcon test --return-code-on-test-failure --packages-select naive naive_superclass
        colcon test-result
